#include "doc_map.h"
#include "doc_html_map.h"

int HTML_ID_Mapping(int id)
{
  switch(id)
  {
    case IDH_svCollections                                     : return IDH_HTML_svCollections;
    case IDH_svCollections_GenericTrees                        : return IDH_HTML_svCollections_GenericTrees;
    case IDH___CLASSES_svCollections_GenericTrees              : return IDH_HTML___CLASSES_svCollections_GenericTrees;
    case IDH_svCollections_GenericTrees_TSVBaseVirtualTreeHelper: return IDH_HTML_svCollections_GenericTrees_TSVBaseVirtualTreeHelper;
    case IDH___MEMBEROVERVIEW_svCollections_GenericTrees_TSVBaseVirtualTreeHelper: return IDH_HTML___MEMBEROVERVIEW_svCollections_GenericTrees_TSVBaseVirtualTreeHelper;
    case IDH___MEMBERTYPE_Methods_svCollections_GenericTrees_TSVBaseVirtualTreeHelper: return IDH_HTML___MEMBERTYPE_Methods_svCollections_GenericTrees_TSVBaseVirtualTreeHelper;
    case IDH_svCollections_GenericTrees_TSVBaseVirtualTreeHelper_GenerateIndex_PVirtualNode: return IDH_HTML_svCollections_GenericTrees_TSVBaseVirtualTreeHelper_GenerateIndex_PVirtualNode;
    case IDH_svCollections_GenericTrees_TSVBaseVirtualTreeHelper_GetSVNode_PVirtualNode_TSVTree_T_: return IDH_HTML_svCollections_GenericTrees_TSVBaseVirtualTreeHelper_GetSVNode_PVirtualNode_TSVTree_T_;
    case IDH_svCollections_GenericTrees_TSVTree                : return IDH_HTML_svCollections_GenericTrees_TSVTree;
    case IDH___MEMBEROVERVIEW_svCollections_GenericTrees_TSVTree: return IDH_HTML___MEMBEROVERVIEW_svCollections_GenericTrees_TSVTree;
    case IDH_svCollections_GenericTrees_TSVTree_Create_Boolean_Integer: return IDH_HTML_svCollections_GenericTrees_TSVTree_Create_Boolean_Integer;
    case IDH_svCollections_GenericTrees_TSVTree_Destroy        : return IDH_HTML_svCollections_GenericTrees_TSVTree_Destroy;
    case IDH___MEMBERTYPE_Methods_svCollections_GenericTrees_TSVTree: return IDH_HTML___MEMBERTYPE_Methods_svCollections_GenericTrees_TSVTree;
    case IDH_svCollections_GenericTrees_TSVTree_AbsoluteIndex_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_AbsoluteIndex_TSVTreeNode_T_;
    case IDH_svCollections_GenericTrees_TSVTree_AddChild_TSVTreeNode_T__T: return IDH_HTML_svCollections_GenericTrees_TSVTree_AddChild_TSVTreeNode_T__T;
    case IDH_svCollections_GenericTrees_TSVTree_BeginUpdate    : return IDH_HTML_svCollections_GenericTrees_TSVTree_BeginUpdate;
    case IDH_svCollections_GenericTrees_TSVTree_Clear          : return IDH_HTML_svCollections_GenericTrees_TSVTree_Clear;
    case IDH_svCollections_GenericTrees_TSVTree_CompactIndex   : return IDH_HTML_svCollections_GenericTrees_TSVTree_CompactIndex;
    case IDH_svCollections_GenericTrees_TSVTree_DeleteChildren_TSVTreeNode_T__Boolean: return IDH_HTML_svCollections_GenericTrees_TSVTree_DeleteChildren_TSVTreeNode_T__Boolean;
    case IDH_svCollections_GenericTrees_TSVTree_DeleteNode_TSVTreeNode_T__Boolean: return IDH_HTML_svCollections_GenericTrees_TSVTree_DeleteNode_TSVTreeNode_T__Boolean;
    case IDH_svCollections_GenericTrees_TSVTree_DoLoadUserData_TSVTreeNode_T__TStream: return IDH_HTML_svCollections_GenericTrees_TSVTree_DoLoadUserData_TSVTreeNode_T__TStream;
    case IDH_svCollections_GenericTrees_TSVTree_DoSaveUserData_TSVTreeNode_T__TStream: return IDH_HTML_svCollections_GenericTrees_TSVTree_DoSaveUserData_TSVTreeNode_T__TStream;
    case IDH_svCollections_GenericTrees_TSVTree_EndUpdate      : return IDH_HTML_svCollections_GenericTrees_TSVTree_EndUpdate;
    case IDH_svCollections_GenericTrees_TSVTree_FinishChunkHeader_TStream_Integer_Integer: return IDH_HTML_svCollections_GenericTrees_TSVTree_FinishChunkHeader_TStream_Integer_Integer;
    case IDH_svCollections_GenericTrees_TSVTree_GenerateIndex_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_GenerateIndex_TSVTreeNode_T_;
    case IDH_svCollections_GenericTrees_TSVTree_GetFirst       : return IDH_HTML_svCollections_GenericTrees_TSVTree_GetFirst;
    case IDH_svCollections_GenericTrees_TSVTree_GetFirstLevel_Integer: return IDH_HTML_svCollections_GenericTrees_TSVTree_GetFirstLevel_Integer;
    case IDH_svCollections_GenericTrees_TSVTree_GetLast_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_GetLast_TSVTreeNode_T_;
    case IDH_svCollections_GenericTrees_TSVTree_GetLastChild_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_GetLastChild_TSVTreeNode_T_;
    case IDH_svCollections_GenericTrees_TSVTree_GetNext_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_GetNext_TSVTreeNode_T_;
    case IDH_svCollections_GenericTrees_TSVTree_GetNextLevel_TSVTreeNode_T__Integer: return IDH_HTML_svCollections_GenericTrees_TSVTree_GetNextLevel_TSVTreeNode_T__Integer;
    case IDH___OVERLOADED_GetNode_svCollections_GenericTrees_TSVTree: return IDH_HTML___OVERLOADED_GetNode_svCollections_GenericTrees_TSVTree;
    case IDH_svCollections_GenericTrees_TSVTree_GetNode_PVirtualNode: return IDH_HTML_svCollections_GenericTrees_TSVTree_GetNode_PVirtualNode;
    case IDH_svCollections_GenericTrees_TSVTree_GetNode_RawByteString: return IDH_HTML_svCollections_GenericTrees_TSVTree_GetNode_RawByteString;
    case IDH_svCollections_GenericTrees_TSVTree_GetNodeLevel_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_GetNodeLevel_TSVTreeNode_T_;
    case IDH_svCollections_GenericTrees_TSVTree_GetPrevious_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_GetPrevious_TSVTreeNode_T_;
    case IDH_svCollections_GenericTrees_TSVTree_GetPreviousLevel_TSVTreeNode_T__Integer: return IDH_HTML_svCollections_GenericTrees_TSVTree_GetPreviousLevel_TSVTreeNode_T__Integer;
    case IDH_svCollections_GenericTrees_TSVTree_HasChildren_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_HasChildren_TSVTreeNode_T_;
    case IDH_svCollections_GenericTrees_TSVTree_HasParent_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_HasParent_TSVTreeNode_T_;
    case IDH_svCollections_GenericTrees_TSVTree_InitNode_TSVTreeNode_T__T: return IDH_HTML_svCollections_GenericTrees_TSVTree_InitNode_TSVTreeNode_T__T;
    case IDH_svCollections_GenericTrees_TSVTree_InternalAddFromStream_TStream_Integer_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_InternalAddFromStream_TStream_Integer_TSVTreeNode_T_;
    case IDH_svCollections_GenericTrees_TSVTree_InternalDeleteNode_TSVTreeNode_T__Boolean: return IDH_HTML_svCollections_GenericTrees_TSVTree_InternalDeleteNode_TSVTreeNode_T__Boolean;
    case IDH_svCollections_GenericTrees_TSVTree_IsRootNode_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_IsRootNode_TSVTreeNode_T_;
    case IDH_svCollections_GenericTrees_TSVTree_IterateSubtree_TSVTreeNode_T__TIterCallback_T__Pointer: return IDH_HTML_svCollections_GenericTrees_TSVTree_IterateSubtree_TSVTreeNode_T__TIterCallback_T__Pointer;
    case IDH_svCollections_GenericTrees_TSVTree_LoadFromFile_TFileName: return IDH_HTML_svCollections_GenericTrees_TSVTree_LoadFromFile_TFileName;
    case IDH_svCollections_GenericTrees_TSVTree_LoadFromStream_TStream: return IDH_HTML_svCollections_GenericTrees_TSVTree_LoadFromStream_TStream;
    case IDH_svCollections_GenericTrees_TSVTree_ProcessNode_TSVTreeNode_T__Boolean: return IDH_HTML_svCollections_GenericTrees_TSVTree_ProcessNode_TSVTreeNode_T__Boolean;
    case IDH_svCollections_GenericTrees_TSVTree_ProcessNodeAddIndex_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_ProcessNodeAddIndex_TSVTreeNode_T_;
    case IDH_svCollections_GenericTrees_TSVTree_ReadChunk_TStream_Integer_TSVTreeNode_T__Integer_Integ: return IDH_HTML_svCollections_GenericTrees_TSVTree_ReadChunk_TStream_Integer_TSVTreeNode_T__Integer_Integ;
    case IDH_svCollections_GenericTrees_TSVTree_ReadNode_TStream_Integer_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_ReadNode_TStream_Integer_TSVTreeNode_T_;
    case IDH_svCollections_GenericTrees_TSVTree_RebuildIndexes_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_RebuildIndexes_TSVTreeNode_T_;
    case IDH_svCollections_GenericTrees_TSVTree_RebuildVirtualTree_PVirtualNode: return IDH_HTML_svCollections_GenericTrees_TSVTree_RebuildVirtualTree_PVirtualNode;
    case IDH_svCollections_GenericTrees_TSVTree_SaveToFile_TFileName: return IDH_HTML_svCollections_GenericTrees_TSVTree_SaveToFile_TFileName;
    case IDH_svCollections_GenericTrees_TSVTree_SaveToStream_TStream_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_SaveToStream_TStream_TSVTreeNode_T_;
    case IDH_svCollections_GenericTrees_TSVTree_WriteChunks_TStream_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_WriteChunks_TStream_TSVTreeNode_T_;
    case IDH_svCollections_GenericTrees_TSVTree_WriteNode_TStream_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTree_WriteNode_TStream_TSVTreeNode_T_;
    case IDH___MEMBERTYPE_Properties_svCollections_GenericTrees_TSVTree: return IDH_HTML___MEMBERTYPE_Properties_svCollections_GenericTrees_TSVTree;
    case IDH_svCollections_GenericTrees_TSVTree_IsEmpty        : return IDH_HTML_svCollections_GenericTrees_TSVTree_IsEmpty;
    case IDH_svCollections_GenericTrees_TSVTree_OnAfterAddChild: return IDH_HTML_svCollections_GenericTrees_TSVTree_OnAfterAddChild;
    case IDH_svCollections_GenericTrees_TSVTree_OnFreeNode     : return IDH_HTML_svCollections_GenericTrees_TSVTree_OnFreeNode;
    case IDH_svCollections_GenericTrees_TSVTree_OnLoadNode     : return IDH_HTML_svCollections_GenericTrees_TSVTree_OnLoadNode;
    case IDH_svCollections_GenericTrees_TSVTree_OnLoadTree     : return IDH_HTML_svCollections_GenericTrees_TSVTree_OnLoadTree;
    case IDH_svCollections_GenericTrees_TSVTree_OnSaveNode     : return IDH_HTML_svCollections_GenericTrees_TSVTree_OnSaveNode;
    case IDH_svCollections_GenericTrees_TSVTree_OnSaveTree     : return IDH_HTML_svCollections_GenericTrees_TSVTree_OnSaveTree;
    case IDH_svCollections_GenericTrees_TSVTree_OwnsObjects    : return IDH_HTML_svCollections_GenericTrees_TSVTree_OwnsObjects;
    case IDH_svCollections_GenericTrees_TSVTree_RootNode       : return IDH_HTML_svCollections_GenericTrees_TSVTree_RootNode;
    case IDH_svCollections_GenericTrees_TSVTree_RootNodeCount  : return IDH_HTML_svCollections_GenericTrees_TSVTree_RootNodeCount;
    case IDH_svCollections_GenericTrees_TSVTree_TotalCount     : return IDH_HTML_svCollections_GenericTrees_TSVTree_TotalCount;
    case IDH_svCollections_GenericTrees_TSVTree_VirtualTree    : return IDH_HTML_svCollections_GenericTrees_TSVTree_VirtualTree;
    case IDH_svCollections_GenericTrees_TSVTreeNode            : return IDH_HTML_svCollections_GenericTrees_TSVTreeNode;
    case IDH___MEMBEROVERVIEW_svCollections_GenericTrees_TSVTreeNode: return IDH_HTML___MEMBEROVERVIEW_svCollections_GenericTrees_TSVTreeNode;
    case IDH___MEMBERTYPE_Fields_svCollections_GenericTrees_TSVTreeNode: return IDH_HTML___MEMBERTYPE_Fields_svCollections_GenericTrees_TSVTreeNode;
    case IDH_svCollections_GenericTrees_TSVTreeNode_FChildCount: return IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FChildCount;
    case IDH_svCollections_GenericTrees_TSVTreeNode_FFirstChild: return IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FFirstChild;
    case IDH_svCollections_GenericTrees_TSVTreeNode_FLastChild : return IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FLastChild;
    case IDH_svCollections_GenericTrees_TSVTreeNode_FNextSibling: return IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FNextSibling;
    case IDH_svCollections_GenericTrees_TSVTreeNode_FNodeIndex : return IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FNodeIndex;
    case IDH_svCollections_GenericTrees_TSVTreeNode_FParent    : return IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FParent;
    case IDH_svCollections_GenericTrees_TSVTreeNode_FPrevSibling: return IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FPrevSibling;
    case IDH_svCollections_GenericTrees_TSVTreeNode_FTotalCount: return IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FTotalCount;
    case IDH_svCollections_GenericTrees_TSVTreeNode_FValue     : return IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FValue;
    case IDH_svCollections_GenericTrees_TSVTreeNode_FVirtualNode: return IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FVirtualNode;
    case IDH___MEMBERTYPE_Methods_svCollections_GenericTrees_TSVTreeNode: return IDH_HTML___MEMBERTYPE_Methods_svCollections_GenericTrees_TSVTreeNode;
    case IDH_svCollections_GenericTrees_TSVTreeNode_GetOwner   : return IDH_HTML_svCollections_GenericTrees_TSVTreeNode_GetOwner;
    case IDH_svCollections_GenericTrees_TSVTreeNode_HasChildren: return IDH_HTML_svCollections_GenericTrees_TSVTreeNode_HasChildren;
    case IDH_svCollections_GenericTrees_TSVTreeNode_HasParent  : return IDH_HTML_svCollections_GenericTrees_TSVTreeNode_HasParent;
    case IDH_svCollections_GenericTrees_TSVTreeNode_SVTreeFromNode_TSVTreeNode_T_: return IDH_HTML_svCollections_GenericTrees_TSVTreeNode_SVTreeFromNode_TSVTreeNode_T_;
    case IDH___RECORDS_svCollections_GenericTrees              : return IDH_HTML___RECORDS_svCollections_GenericTrees;
    case IDH_svCollections_GenericTrees_TSVBaseChunk           : return IDH_HTML_svCollections_GenericTrees_TSVBaseChunk;
    case IDH_svCollections_GenericTrees_TSVBaseChunkBody       : return IDH_HTML_svCollections_GenericTrees_TSVBaseChunkBody;
    case IDH_svCollections_GenericTrees_TSVChunkHeader         : return IDH_HTML_svCollections_GenericTrees_TSVChunkHeader;
    case IDH___TYPES_svCollections_GenericTrees                : return IDH_HTML___TYPES_svCollections_GenericTrees;
    case IDH_svCollections_GenericTrees_ProcAfterAddNode       : return IDH_HTML_svCollections_GenericTrees_ProcAfterAddNode;
    case IDH_svCollections_GenericTrees_ProcOnFreeNode         : return IDH_HTML_svCollections_GenericTrees_ProcOnFreeNode;
    case IDH_svCollections_GenericTrees_ProcOnSaveNode         : return IDH_HTML_svCollections_GenericTrees_ProcOnSaveNode;
    case IDH_svCollections_GenericTrees_ProcSaveTree           : return IDH_HTML_svCollections_GenericTrees_ProcSaveTree;
    case IDH_svCollections_GenericTrees_TIterCallBack          : return IDH_HTML_svCollections_GenericTrees_TIterCallBack;
    case IDH_svCollections_GenericTrees_TSVMagicID             : return IDH_HTML_svCollections_GenericTrees_TSVMagicID;
    case IDH___CONSTANTS_svCollections_GenericTrees            : return IDH_HTML___CONSTANTS_svCollections_GenericTrees;
    case IDH_svCollections_GenericTrees_BaseChunk              : return IDH_HTML_svCollections_GenericTrees_BaseChunk;
    case IDH_svCollections_GenericTrees_CaptionChunk           : return IDH_HTML_svCollections_GenericTrees_CaptionChunk;
    case IDH_svCollections_GenericTrees_NodeChunk              : return IDH_HTML_svCollections_GenericTrees_NodeChunk;
    case IDH_svCollections_GenericTrees_SVMagicID              : return IDH_HTML_svCollections_GenericTrees_SVMagicID;
    case IDH_svCollections_GenericTrees_SVTreeStreamVersion    : return IDH_HTML_svCollections_GenericTrees_SVTreeStreamVersion;
    case IDH_svCollections_GenericTrees_UserChunk              : return IDH_HTML_svCollections_GenericTrees_UserChunk;
    case IDH_svCollections_Trees                               : return IDH_HTML_svCollections_Trees;
    case IDH___CLASSES_svCollections_Trees                     : return IDH_HTML___CLASSES_svCollections_Trees;
    case IDH_svCollections_Trees_TSVBaseVirtualTreeHelper      : return IDH_HTML_svCollections_Trees_TSVBaseVirtualTreeHelper;
    case IDH___MEMBEROVERVIEW_svCollections_Trees_TSVBaseVirtualTreeHelper: return IDH_HTML___MEMBEROVERVIEW_svCollections_Trees_TSVBaseVirtualTreeHelper;
    case IDH___MEMBERTYPE_Methods_svCollections_Trees_TSVBaseVirtualTreeHelper: return IDH_HTML___MEMBERTYPE_Methods_svCollections_Trees_TSVBaseVirtualTreeHelper;
    case IDH_svCollections_Trees_TSVBaseVirtualTreeHelper_GenerateIndex_PVirtualNode: return IDH_HTML_svCollections_Trees_TSVBaseVirtualTreeHelper_GenerateIndex_PVirtualNode;
    case IDH_svCollections_Trees_TSVBaseVirtualTreeHelper_GetSVNode_PVirtualNode_TSVTree: return IDH_HTML_svCollections_Trees_TSVBaseVirtualTreeHelper_GetSVNode_PVirtualNode_TSVTree;
    case IDH_svCollections_Trees_TSVTree                       : return IDH_HTML_svCollections_Trees_TSVTree;
    case IDH___MEMBEROVERVIEW_svCollections_Trees_TSVTree      : return IDH_HTML___MEMBEROVERVIEW_svCollections_Trees_TSVTree;
    case IDH_svCollections_Trees_TSVTree_Create_Boolean_Integer: return IDH_HTML_svCollections_Trees_TSVTree_Create_Boolean_Integer;
    case IDH_svCollections_Trees_TSVTree_Destroy               : return IDH_HTML_svCollections_Trees_TSVTree_Destroy;
    case IDH___MEMBERTYPE_Methods_svCollections_Trees_TSVTree  : return IDH_HTML___MEMBERTYPE_Methods_svCollections_Trees_TSVTree;
    case IDH_svCollections_Trees_TSVTree_AbsoluteIndex_PSVTreeNode: return IDH_HTML_svCollections_Trees_TSVTree_AbsoluteIndex_PSVTreeNode;
    case IDH_svCollections_Trees_TSVTree_AddChild_PSVTreeNode_Pointer: return IDH_HTML_svCollections_Trees_TSVTree_AddChild_PSVTreeNode_Pointer;
    case IDH_svCollections_Trees_TSVTree_BeginUpdate           : return IDH_HTML_svCollections_Trees_TSVTree_BeginUpdate;
    case IDH_svCollections_Trees_TSVTree_Clear                 : return IDH_HTML_svCollections_Trees_TSVTree_Clear;
    case IDH_svCollections_Trees_TSVTree_CompactIndex          : return IDH_HTML_svCollections_Trees_TSVTree_CompactIndex;
    case IDH_svCollections_Trees_TSVTree_DeleteChildren_PSVTreeNode_Boolean: return IDH_HTML_svCollections_Trees_TSVTree_DeleteChildren_PSVTreeNode_Boolean;
    case IDH_svCollections_Trees_TSVTree_DeleteNode_PSVTreeNode_Boolean: return IDH_HTML_svCollections_Trees_TSVTree_DeleteNode_PSVTreeNode_Boolean;
    case IDH_svCollections_Trees_TSVTree_DoLoadUserData_PSVTreeNode_TStream: return IDH_HTML_svCollections_Trees_TSVTree_DoLoadUserData_PSVTreeNode_TStream;
    case IDH_svCollections_Trees_TSVTree_DoSaveUserData_PSVTreeNode_TStream: return IDH_HTML_svCollections_Trees_TSVTree_DoSaveUserData_PSVTreeNode_TStream;
    case IDH_svCollections_Trees_TSVTree_EndUpdate             : return IDH_HTML_svCollections_Trees_TSVTree_EndUpdate;
    case IDH_svCollections_Trees_TSVTree_FindNode_string       : return IDH_HTML_svCollections_Trees_TSVTree_FindNode_string;
    case IDH_svCollections_Trees_TSVTree_FinishChunkHeader_TStream_Integer_Integer: return IDH_HTML_svCollections_Trees_TSVTree_FinishChunkHeader_TStream_Integer_Integer;
    case IDH_svCollections_Trees_TSVTree_GenerateIndex_PSVTreeNode: return IDH_HTML_svCollections_Trees_TSVTree_GenerateIndex_PSVTreeNode;
    case IDH_svCollections_Trees_TSVTree_GetFirst              : return IDH_HTML_svCollections_Trees_TSVTree_GetFirst;
    case IDH_svCollections_Trees_TSVTree_GetFirstLevel_Integer : return IDH_HTML_svCollections_Trees_TSVTree_GetFirstLevel_Integer;
    case IDH_svCollections_Trees_TSVTree_GetLast_PSVTreeNode   : return IDH_HTML_svCollections_Trees_TSVTree_GetLast_PSVTreeNode;
    case IDH_svCollections_Trees_TSVTree_GetLastChild_PSVTreeNode: return IDH_HTML_svCollections_Trees_TSVTree_GetLastChild_PSVTreeNode;
    case IDH_svCollections_Trees_TSVTree_GetNext_PSVTreeNode   : return IDH_HTML_svCollections_Trees_TSVTree_GetNext_PSVTreeNode;
    case IDH_svCollections_Trees_TSVTree_GetNextLevel_PSVTreeNode_Integer: return IDH_HTML_svCollections_Trees_TSVTree_GetNextLevel_PSVTreeNode_Integer;
    case IDH___OVERLOADED_GetNode_svCollections_Trees_TSVTree  : return IDH_HTML___OVERLOADED_GetNode_svCollections_Trees_TSVTree;
    case IDH_svCollections_Trees_TSVTree_GetNode_PVirtualNode  : return IDH_HTML_svCollections_Trees_TSVTree_GetNode_PVirtualNode;
    case IDH_svCollections_Trees_TSVTree_GetNode_RawByteString : return IDH_HTML_svCollections_Trees_TSVTree_GetNode_RawByteString;
    case IDH_svCollections_Trees_TSVTree_GetNodeLevel_PSVTreeNode: return IDH_HTML_svCollections_Trees_TSVTree_GetNodeLevel_PSVTreeNode;
    case IDH_svCollections_Trees_TSVTree_GetPrevious_PSVTreeNode: return IDH_HTML_svCollections_Trees_TSVTree_GetPrevious_PSVTreeNode;
    case IDH_svCollections_Trees_TSVTree_GetPreviousLevel_PSVTreeNode_Integer: return IDH_HTML_svCollections_Trees_TSVTree_GetPreviousLevel_PSVTreeNode_Integer;
    case IDH_svCollections_Trees_TSVTree_HasChildren_PSVTreeNode: return IDH_HTML_svCollections_Trees_TSVTree_HasChildren_PSVTreeNode;
    case IDH_svCollections_Trees_TSVTree_HasParent_PSVTreeNode : return IDH_HTML_svCollections_Trees_TSVTree_HasParent_PSVTreeNode;
    case IDH_svCollections_Trees_TSVTree_InitNode_PSVTreeNode_Pointer: return IDH_HTML_svCollections_Trees_TSVTree_InitNode_PSVTreeNode_Pointer;
    case IDH_svCollections_Trees_TSVTree_InternalAddFromStream_TStream_Integer_PSVTreeNode: return IDH_HTML_svCollections_Trees_TSVTree_InternalAddFromStream_TStream_Integer_PSVTreeNode;
    case IDH_svCollections_Trees_TSVTree_InternalDeleteNode_PSVTreeNode_Boolean: return IDH_HTML_svCollections_Trees_TSVTree_InternalDeleteNode_PSVTreeNode_Boolean;
    case IDH_svCollections_Trees_TSVTree_IsRootNode_PSVTreeNode: return IDH_HTML_svCollections_Trees_TSVTree_IsRootNode_PSVTreeNode;
    case IDH_svCollections_Trees_TSVTree_IterateSubtree_PSVTreeNode_TIterCallback_Pointer: return IDH_HTML_svCollections_Trees_TSVTree_IterateSubtree_PSVTreeNode_TIterCallback_Pointer;
    case IDH_svCollections_Trees_TSVTree_LoadFromFile_TFileName: return IDH_HTML_svCollections_Trees_TSVTree_LoadFromFile_TFileName;
    case IDH_svCollections_Trees_TSVTree_LoadFromStream_TStream: return IDH_HTML_svCollections_Trees_TSVTree_LoadFromStream_TStream;
    case IDH_svCollections_Trees_TSVTree_ReadChunk_TStream_Integer_PSVTreeNode_Integer_Integer: return IDH_HTML_svCollections_Trees_TSVTree_ReadChunk_TStream_Integer_PSVTreeNode_Integer_Integer;
    case IDH_svCollections_Trees_TSVTree_ReadNode_TStream_Integer_PSVTreeNode: return IDH_HTML_svCollections_Trees_TSVTree_ReadNode_TStream_Integer_PSVTreeNode;
    case IDH_svCollections_Trees_TSVTree_RebuildIndexes_PSVTreeNode: return IDH_HTML_svCollections_Trees_TSVTree_RebuildIndexes_PSVTreeNode;
    case IDH_svCollections_Trees_TSVTree_RebuildVirtualTree_PVirtualNode: return IDH_HTML_svCollections_Trees_TSVTree_RebuildVirtualTree_PVirtualNode;
    case IDH_svCollections_Trees_TSVTree_SaveToFile_TFileName  : return IDH_HTML_svCollections_Trees_TSVTree_SaveToFile_TFileName;
    case IDH_svCollections_Trees_TSVTree_SaveToStream_TStream_PSVTreeNode: return IDH_HTML_svCollections_Trees_TSVTree_SaveToStream_TStream_PSVTreeNode;
    case IDH_svCollections_Trees_TSVTree_WriteChunks_TStream_PSVTreeNode: return IDH_HTML_svCollections_Trees_TSVTree_WriteChunks_TStream_PSVTreeNode;
    case IDH_svCollections_Trees_TSVTree_WriteNode_TStream_PSVTreeNode: return IDH_HTML_svCollections_Trees_TSVTree_WriteNode_TStream_PSVTreeNode;
    case IDH___MEMBERTYPE_Properties_svCollections_Trees_TSVTree: return IDH_HTML___MEMBERTYPE_Properties_svCollections_Trees_TSVTree;
    case IDH_svCollections_Trees_TSVTree_IsEmpty               : return IDH_HTML_svCollections_Trees_TSVTree_IsEmpty;
    case IDH_svCollections_Trees_TSVTree_OwnsObjects           : return IDH_HTML_svCollections_Trees_TSVTree_OwnsObjects;
    case IDH_svCollections_Trees_TSVTree_RootNode              : return IDH_HTML_svCollections_Trees_TSVTree_RootNode;
    case IDH_svCollections_Trees_TSVTree_RootNodeCount         : return IDH_HTML_svCollections_Trees_TSVTree_RootNodeCount;
    case IDH_svCollections_Trees_TSVTree_TotalCount            : return IDH_HTML_svCollections_Trees_TSVTree_TotalCount;
    case IDH_svCollections_Trees_TSVTree_UseCustomIndex        : return IDH_HTML_svCollections_Trees_TSVTree_UseCustomIndex;
    case IDH_svCollections_Trees_TSVTree_VirtualTree           : return IDH_HTML_svCollections_Trees_TSVTree_VirtualTree;
    case IDH___MEMBERTYPE_Events_svCollections_Trees_TSVTree   : return IDH_HTML___MEMBERTYPE_Events_svCollections_Trees_TSVTree;
    case IDH_svCollections_Trees_TSVTree_OnAfterAddChild       : return IDH_HTML_svCollections_Trees_TSVTree_OnAfterAddChild;
    case IDH_svCollections_Trees_TSVTree_OnFreeNode            : return IDH_HTML_svCollections_Trees_TSVTree_OnFreeNode;
    case IDH_svCollections_Trees_TSVTree_OnLoadNode            : return IDH_HTML_svCollections_Trees_TSVTree_OnLoadNode;
    case IDH_svCollections_Trees_TSVTree_OnLoadTree            : return IDH_HTML_svCollections_Trees_TSVTree_OnLoadTree;
    case IDH_svCollections_Trees_TSVTree_OnSaveNode            : return IDH_HTML_svCollections_Trees_TSVTree_OnSaveNode;
    case IDH_svCollections_Trees_TSVTree_OnSaveTree            : return IDH_HTML_svCollections_Trees_TSVTree_OnSaveTree;
    case IDH_svCollections_Trees_TSVTreeNode                   : return IDH_HTML_svCollections_Trees_TSVTreeNode;
    case IDH___MEMBEROVERVIEW_svCollections_Trees_TSVTreeNode  : return IDH_HTML___MEMBEROVERVIEW_svCollections_Trees_TSVTreeNode;
    case IDH___MEMBERTYPE_Fields_svCollections_Trees_TSVTreeNode: return IDH_HTML___MEMBERTYPE_Fields_svCollections_Trees_TSVTreeNode;
    case IDH_svCollections_Trees_TSVTreeNode_FChildCount       : return IDH_HTML_svCollections_Trees_TSVTreeNode_FChildCount;
    case IDH_svCollections_Trees_TSVTreeNode_FFirstChild       : return IDH_HTML_svCollections_Trees_TSVTreeNode_FFirstChild;
    case IDH_svCollections_Trees_TSVTreeNode_FLastChild        : return IDH_HTML_svCollections_Trees_TSVTreeNode_FLastChild;
    case IDH_svCollections_Trees_TSVTreeNode_FNextSibling      : return IDH_HTML_svCollections_Trees_TSVTreeNode_FNextSibling;
    case IDH_svCollections_Trees_TSVTreeNode_FNodeIndex        : return IDH_HTML_svCollections_Trees_TSVTreeNode_FNodeIndex;
    case IDH_svCollections_Trees_TSVTreeNode_FParent           : return IDH_HTML_svCollections_Trees_TSVTreeNode_FParent;
    case IDH_svCollections_Trees_TSVTreeNode_FPrevSibling      : return IDH_HTML_svCollections_Trees_TSVTreeNode_FPrevSibling;
    case IDH_svCollections_Trees_TSVTreeNode_FTotalCount       : return IDH_HTML_svCollections_Trees_TSVTreeNode_FTotalCount;
    case IDH_svCollections_Trees_TSVTreeNode_FValue            : return IDH_HTML_svCollections_Trees_TSVTreeNode_FValue;
    case IDH_svCollections_Trees_TSVTreeNode_FVirtualNode      : return IDH_HTML_svCollections_Trees_TSVTreeNode_FVirtualNode;
    case IDH___MEMBERTYPE_Methods_svCollections_Trees_TSVTreeNode: return IDH_HTML___MEMBERTYPE_Methods_svCollections_Trees_TSVTreeNode;
    case IDH_svCollections_Trees_TSVTreeNode_GetOwner          : return IDH_HTML_svCollections_Trees_TSVTreeNode_GetOwner;
    case IDH_svCollections_Trees_TSVTreeNode_HasChildren       : return IDH_HTML_svCollections_Trees_TSVTreeNode_HasChildren;
    case IDH_svCollections_Trees_TSVTreeNode_HasParent         : return IDH_HTML_svCollections_Trees_TSVTreeNode_HasParent;
    case IDH___FUNCTIONS_svCollections_Trees                   : return IDH_HTML___FUNCTIONS_svCollections_Trees;
    case IDH_svCollections_Trees_SVTreeFromNode_PSVTreeNode    : return IDH_HTML_svCollections_Trees_SVTreeFromNode_PSVTreeNode;
    case IDH___RECORDS_svCollections_Trees                     : return IDH_HTML___RECORDS_svCollections_Trees;
    case IDH_svCollections_Trees_TSVBaseChunk                  : return IDH_HTML_svCollections_Trees_TSVBaseChunk;
    case IDH_svCollections_Trees_TSVBaseChunkBody              : return IDH_HTML_svCollections_Trees_TSVBaseChunkBody;
    case IDH_svCollections_Trees_TSVChunkHeader                : return IDH_HTML_svCollections_Trees_TSVChunkHeader;
    case IDH___TYPES_svCollections_Trees                       : return IDH_HTML___TYPES_svCollections_Trees;
    case IDH_svCollections_Trees_ProcAfterAddNode              : return IDH_HTML_svCollections_Trees_ProcAfterAddNode;
    case IDH_svCollections_Trees_ProcOnFreeNode                : return IDH_HTML_svCollections_Trees_ProcOnFreeNode;
    case IDH_svCollections_Trees_ProcOnSaveNode                : return IDH_HTML_svCollections_Trees_ProcOnSaveNode;
    case IDH_svCollections_Trees_ProcSaveTree                  : return IDH_HTML_svCollections_Trees_ProcSaveTree;
    case IDH_svCollections_Trees_PSVTreeNode                   : return IDH_HTML_svCollections_Trees_PSVTreeNode;
    case IDH_svCollections_Trees_TIterCallBack                 : return IDH_HTML_svCollections_Trees_TIterCallBack;
    case IDH_svCollections_Trees_TSVMagicID                    : return IDH_HTML_svCollections_Trees_TSVMagicID;
    case IDH___CONSTANTS_svCollections_Trees                   : return IDH_HTML___CONSTANTS_svCollections_Trees;
    case IDH_svCollections_Trees_BaseChunk                     : return IDH_HTML_svCollections_Trees_BaseChunk;
    case IDH_svCollections_Trees_CaptionChunk                  : return IDH_HTML_svCollections_Trees_CaptionChunk;
    case IDH_svCollections_Trees_NodeChunk                     : return IDH_HTML_svCollections_Trees_NodeChunk;
    case IDH_svCollections_Trees_SVMagicID                     : return IDH_HTML_svCollections_Trees_SVMagicID;
    case IDH_svCollections_Trees_SVTreeStreamVersion           : return IDH_HTML_svCollections_Trees_SVTreeStreamVersion;
    case IDH_svCollections_Trees_UserChunk                     : return IDH_HTML_svCollections_Trees_UserChunk;
    case IDH___FILES                                           : return IDH_HTML___FILES;
    case IDH_svCollections_GenericTrees_pas                    : return IDH_HTML_svCollections_GenericTrees_pas;
    case IDH_svCollections_Trees_pas                           : return IDH_HTML_svCollections_Trees_pas;
    default: return -1;
  }
}
