unit TestSvSerializerJsonFactory;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, SysUtils, SvSerializer, SvSerializerJsonFactory,
  Classes, Generics.Collections, Graphics, uSvStrings;

type
  TDemoEnum = (deOne, deTwo, deThree);

  TNumbers = set of TDemoEnum;

  TMyRec = record
  private
    FString: string;
    FInt: Integer;
    procedure SetString(const Value: string);
    procedure SetInt(const Value: Integer);
  public
    [SvSerialize]
    property AInt: Integer read FInt write SetInt;
    [SvSerialize]
    property AString: string read FString write SetString;
  end;

  IDemoObj = interface
  ['{045BBB1C-89AC-4FAF-9B60-14DC79CCB5FC}']
    function GetName: string;
    procedure SetName(const Value: string);
    [SvSerialize]
    property Name: string read GetName write SetName;
  end;

  TDemoObj = class(TInterfacedObject, IDemoObj)
  private
    FName: string;
    FTag: Integer;
    FDate: TDateTime;
    FEnumas: TDemoEnum;
    FMas: TArray<string>;
    FValue: Variant;
    FIsValid: Boolean;
    FList: TStrings;
    FList2: TList<Integer>;
    FMyRec: TMyRec;
    FColor: TColor;
    FFont: TFont;
    FIntf: IDemoObj;
    FMeth: TProc;
    FDouble: Double;
    FSet: TNumbers;
    FMas2: TArray<TMyRec>;
    FSvString: TSvString;
    FDict: TDictionary<string, TMyRec>;
    function GetName: string;
    procedure SetName(const Value: string);
  public
    constructor Create();
    destructor Destroy; override;
    [SvSerialize]
    property ASet: TNumbers read FSet write FSet;
    [SvSerialize]
    property Name: string read GetName write SetName;
    [SvSerialize]
    property Tag: Integer read FTag write FTag;
    [SvSerialize]
    property DoubleVal: Double read FDouble write FDouble;
    [SvSerialize]
    property Date: TDateTime read FDate write FDate;
    [SvSerialize]
    property Enumas: TDemoEnum read FEnumas write FEnumas;
    [SvSerialize]
    property Mas: TArray<string> read FMas write FMas;
    [SvSerialize]
    property Mas2: TArray<TMyRec> read FMas2 write FMas2;
    [SvSerialize]
    property Value: Variant read FValue write FValue;
    [SvSerialize]
    property IsValid: Boolean read FIsValid write FIsValid;
    [SvSerialize]
    property List: TStrings read FList write FList;
    [SvSerialize]
    property List2: TList<Integer> read FList2 write FList2;
    [SvSerialize]
    property MyRec: TMyRec read FMyRec write FMyRec;
    [SvSerialize]
    property Color: TColor read FColor write FColor;
    [SvSerialize('MyFont')]
    property Font: TFont read FFont write FFont;
   // [SvSerialize]
    property Intf: IDemoObj read FIntf write FIntf;
    [SvSerialize]
    property Meth: TProc read FMeth write FMeth;
    [SvSerialize]
    property SvString: TSvString read FSvString write FSvString;
    [SvSerialize]
    property Dict: TDictionary<string, TMyRec> read FDict write FDict;
  end;
  // Test methods for class TSvJsonSerializerFactory

  TestTSvJsonSerializerFactory = class(TTestCase)
  strict private
    FSerializer: TSvSerializer;
    FSvJsonSerializerFactory: TSvJsonSerializerFactory;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    //test methods
    procedure TestSerializeAndDeserialize();
    procedure TestAddObjectProperties();
    procedure TestRemoveObject();
    procedure TestSerializeRecord();
  end;

implementation

uses
  Variants,
  DateUtils,
  TypInfo,
  Rtti;

const
  FILE_SERIALIZE = 'TestSerialize.json';

{ TDemoObj }

constructor TDemoObj.Create;
begin
  FName := '';
  Tag := 0;
  Date := Now;
  Enumas := deOne;
  FValue := Unassigned;
  FIsValid := False;
  FList := TStringList.Create;
  FList2 := TList<Integer>.Create;
  FFont := TFont.Create;
  FIntf := nil;
  FDict := TDictionary<string,TMyRec>.Create();
end;

destructor TDemoObj.Destroy;
begin
  FList.Free;
  FList2.Free;
  FFont.Free;
  FDict.Free;
  inherited;
end;

function TDemoObj.GetName: string;
begin
  Result := FName;
end;

procedure TDemoObj.SetName(const Value: string);
begin
  FName := Value;
end;

procedure TestTSvJsonSerializerFactory.SetUp;
begin
  FSerializer := TSvSerializer.Create(sstJson);
  FSvJsonSerializerFactory := TSvJsonSerializerFactory(FSerializer.Factory);
end;

procedure TestTSvJsonSerializerFactory.TearDown;
begin
  FSerializer.Free;
  FSvJsonSerializerFactory := nil;
end;

const
  KEY_VALUE: string = 'Main';

  PROP_STRING = 'Some unicode Português " Русский Ελληνικά';
  PROP_INTEGER : Integer = MaxInt;
  PROP_DOUBLE: Double = 15865874.1569854;
  PROP_ENUM: TDemoEnum = deThree;
  PROP_BOOLEAN: Boolean = True;
  PROP_COLOR: TColor = clRed;
  PROP_SET: TNumbers = [deTwo, deThree];
  PROP_ARRAY: array[0..2] of string = ('1','2','3');
  PROP_FONTNAME = 'Verdana';
  PROP_FONTSIZE = 25;
  COUNT_ARRAY = 3;

procedure TestTSvJsonSerializerFactory.TestAddObjectProperties;
var
  TestObj: TDemoObj;
begin
  TestObj := TDemoObj.Create;
  try
    TestObj.Name := PROP_STRING;
    TestObj.ASet := PROP_SET;
    TestObj.Value := PROP_DOUBLE;
    FSerializer.AddObjectCustomProperties('Test', TestObj, ['Name', 'ASet', 'Value']);

    FSerializer.Serialize('Test.json');


    TestObj.Free;
    TestObj := TDemoObj.Create;

    FSerializer.AddObjectCustomProperties('Test', TestObj, ['Name', 'Value']);

    FSerializer.DeSerialize('Test.json');

    CheckEqualsString(PROP_STRING, TestObj.Name);
    CheckEquals(PROP_DOUBLE, TestObj.Value);
    CheckFalse(PROP_SET = TestObj.ASet);

  finally
    TestObj.Free;
  end;
end;

procedure TestTSvJsonSerializerFactory.TestRemoveObject;
var
  TestObj, TestObj2, temp: TDemoObj;
begin
  TestObj := TDemoObj.Create;
  TestObj2 := TDemoObj.Create;
  try
    FSerializer.AddObject('Test', TestObj);
    FSerializer.AddObject('Test2', TestObj2);

    CheckEquals(2, FSerializer.Count);

    FSerializer.RemoveObject(TestObj);

    CheckEquals(1, FSerializer.Count);

    temp := TDemoObj(FSerializer['Test2'].AsObject);

    CheckTrue(temp = TestObj2);
  finally
    TestObj.Free;
    TestObj2.Free;
  end;
end;

procedure TestTSvJsonSerializerFactory.TestSerializeAndDeserialize;
var
  TestObj: TDemoObj;
  ARec1, ARec2, ARec3: TMyRec;
  AEnum: TPair<string,TMyRec>;
  i: Integer;
begin
  TestObj := TDemoObj.Create;
  try
    //set our properties

    {$REGION 'Set Properties'}
    //string property
    TestObj.Name  := PROP_STRING;
    //integer property
    TestObj.Tag := PROP_INTEGER;
    //datetime property
    TestObj.Date := Today;
    //double property
    TestObj.DoubleVal := PROP_DOUBLE;
    //enum property
    TestObj.Enumas := PROP_ENUM;
    //boolean property
    TestObj.IsValid := PROP_BOOLEAN;
    //TColor property
    TestObj.Color := PROP_COLOR;
    //set property
    TestObj.ASet := PROP_SET;
    //variant property
    TestObj.Value := PROP_DOUBLE;
    //array property
    TestObj.Mas := TArray<string>.Create('1','2','3');
    //complex array
    ARec1.AString := '1';
    ARec1.AInt := 111;
    ARec2.AString := '2';
    ARec2.AInt := 222;
    ARec3.AString := '3';
    ARec3.AInt := 333;
    TestObj.Mas2 := TArray<TMyRec>.Create(ARec1, ARec2, ARec3);
    //TStrings property
    TestObj.List.AddStrings(TestObj.Mas);
    //Generic List property
    TestObj.List2.AddRange([1,2,3]);
    // record property
    TestObj.MyRec.AString := PROP_STRING;
    TestObj.MyRec.AInt := PROP_INTEGER;
    //TFont property
    TestObj.Font.Name := PROP_FONTNAME;
    TestObj.Font.Size := PROP_FONTSIZE;
    //TSvString property
    TestObj.SvString := PROP_STRING;
    //TDictionary property
    TestObj.Dict.Add(PROP_STRING, ARec1);
    TestObj.Dict.Add('1', ARec2);
   // TestObj.Dict.Add(PROP_STRING, PROP_STRING);
   // TestObj.Dict.Add('1', '111');
    {$ENDREGION}


    ///////////////////////////////////////////

    FSerializer.AddObject(KEY_VALUE, TestObj);
    //serialize to file
    FSerializer.Serialize(FILE_SERIALIZE);

    CheckTrue(FileExists(FILE_SERIALIZE));

   // FSerializer.RemoveObject(KEY_VALUE);
    CheckTrue(FSerializer.Count = 0);
    //recreate our object to make sure that it's values reset to their initial state
    TestObj.Free;
    TestObj := TDemoObj.Create;
    //add newly created object
    FSerializer.AddObject(KEY_VALUE, TestObj);
    CheckTrue(FSerializer.Count = 1);
    //deserialize from file
    FSerializer.DeSerialize(FILE_SERIALIZE);
    //check our properties


    {$REGION 'Check Properties'}
    //string property
    CheckEqualsString(TestObj.Name, PROP_STRING);
    //integer property
    CheckEquals(TestObj.Tag, PROP_INTEGER);
    //datetime property
    CheckEquals(TestObj.Date, Today);
    //double property
    CheckEquals(TestObj.DoubleVal, PROP_DOUBLE);
    //enum property
    CheckTrue(TestObj.Enumas = PROP_ENUM);
    //boolean property
    CheckTrue(TestObj.IsValid = PROP_BOOLEAN);
    //TColor property
    CheckEquals(TestObj.Color, PROP_COLOR);
    //set property
    CheckTrue(TestObj.ASet = PROP_SET);
    //variant property
    CheckTrue(TestObj.Value = PROP_DOUBLE);
    //array property
    CheckTrue(Length(TestObj.Mas) = COUNT_ARRAY);
    CheckEqualsString('1', TestObj.Mas[0]);
    CheckEqualsString('2', TestObj.Mas[1]);
    CheckEqualsString('3', TestObj.Mas[2]);
    //complex array property
    CheckTrue(Length(TestObj.Mas2) = COUNT_ARRAY);
    CheckEqualsString('1', TestObj.Mas2[0].AString);
    CheckEqualsString('2', TestObj.Mas2[1].AString);
    CheckEqualsString('3', TestObj.Mas2[2].AString);
    CheckEquals(111, TestObj.Mas2[0].AInt);
    CheckEquals(222, TestObj.Mas2[1].AInt);
    CheckEquals(333, TestObj.Mas2[2].AInt);
    //TStrings property
    CheckEquals(COUNT_ARRAY, TestObj.List.Count);
    CheckEqualsString('1', TestObj.List[0]);
    CheckEqualsString('2', TestObj.List[1]);
    CheckEqualsString('3', TestObj.List[2]);
    //Generic List property
    CheckEquals(COUNT_ARRAY, TestObj.List2.Count);
    CheckEquals(1, TestObj.List2[0]);
    CheckEquals(2, TestObj.List2[1]);
    CheckEquals(3, TestObj.List2[2]);
    // record property
    CheckEqualsString(PROP_STRING, TestObj.MyRec.AString);
    CheckEquals(PROP_INTEGER, TestObj.MyRec.AInt);
    //TFont property
    CheckEqualsString(PROP_FONTNAME, TestObj.Font.Name);
    CheckEquals(PROP_FONTSIZE, TestObj.Font.Size);
    //TSvString property
    CheckEqualsString(PROP_STRING, TestObj.SvString);
    //TDictionary property
 //   CheckTrue(TestObj.Dict.ContainsKey(PROP_STRING));
 //   CheckTrue(TestObj.Dict.ContainsValue(PROP_STRING));
    CheckTrue(TestObj.Dict.ContainsKey(PROP_STRING));
    i := 0;
    for AEnum in TestObj.Dict do
    begin
      if i = 1 then
      begin
        CheckEqualsString(PROP_STRING, AEnum.Key);
        CheckEqualsString(ARec1.AString, AEnum.Value.AString);
        CheckEquals(ARec1.AInt, AEnum.Value.AInt);
      end
      else
      begin
        CheckEqualsString('1', AEnum.Key);
        CheckEqualsString(ARec2.AString, AEnum.Value.AString);
        CheckEquals(ARec2.AInt, AEnum.Value.AInt);
      end;

      Inc(i);
    end;
    {$ENDREGION}


  finally
    TestObj.Free;
  end;
end;

procedure TestTSvJsonSerializerFactory.TestSerializeRecord;
var
  ARec: TMyRec;
begin
  ARec.AString := PROP_STRING;
  ARec.AInt := PROP_INTEGER;

  FSerializer.Marshall<TMyRec>(ARec, 'Record.json');


  ARec.AString := '';
  ARec.AInt := -1;

  ARec := FSerializer.UnMarshall<TMyRec>('Record.json');

  CheckEqualsString(PROP_STRING, ARec.AString);
  CheckEquals(PROP_INTEGER, ARec.AInt);

end;

{ TMyRec }

procedure TMyRec.SetInt(const Value: Integer);
begin
  FInt := Value;
end;

procedure TMyRec.SetString(const Value: string);
begin
  FString := Value;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSvJsonSerializerFactory.Suite);
end.

