#define IDH_HTML_svCollections                             0x00000000 // svCollections
#define IDH_HTML_svCollections_GenericTrees                0x00000001 // svCollections.GenericTrees
#define IDH_HTML___CLASSES_svCollections_GenericTrees      0x00000002 // !!CLASSES_svCollections.GenericTrees
#define IDH_HTML_svCollections_GenericTrees_TSVBaseVirtualTreeHelper 0x00000003 // svCollections.GenericTrees.TSVBaseVirtualTreeHelper
#define IDH_HTML___MEMBEROVERVIEW_svCollections_GenericTrees_TSVBaseVirtualTreeHelper 0x00000004 // !!MEMBEROVERVIEW_svCollections.GenericTrees.TSVBaseVirtualTreeHelper
#define IDH_HTML___MEMBERTYPE_Methods_svCollections_GenericTrees_TSVBaseVirtualTreeHelper 0x00000005 // !!MEMBERTYPE_Methods_svCollections.GenericTrees.TSVBaseVirtualTreeHelper
#define IDH_HTML_svCollections_GenericTrees_TSVBaseVirtualTreeHelper_GenerateIndex_PVirtualNode 0x00000006 // svCollections.GenericTrees.TSVBaseVirtualTreeHelper.GenerateIndex@PVirtualNode
#define IDH_HTML_svCollections_GenericTrees_TSVBaseVirtualTreeHelper_GetSVNode_PVirtualNode_TSVTree_T_ 0x00000007 // svCollections.GenericTrees.TSVBaseVirtualTreeHelper.GetSVNode@PVirtualNode@TSVTree<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree        0x00000008 // svCollections.GenericTrees.TSVTree
#define IDH_HTML___MEMBEROVERVIEW_svCollections_GenericTrees_TSVTree 0x00000009 // !!MEMBEROVERVIEW_svCollections.GenericTrees.TSVTree
#define IDH_HTML_svCollections_GenericTrees_TSVTree_Create_Boolean_Integer 0x0000000A // svCollections.GenericTrees.TSVTree.Create@Boolean@Integer
#define IDH_HTML_svCollections_GenericTrees_TSVTree_Destroy 0x0000000B // svCollections.GenericTrees.TSVTree.Destroy
#define IDH_HTML___MEMBERTYPE_Methods_svCollections_GenericTrees_TSVTree 0x0000000C // !!MEMBERTYPE_Methods_svCollections.GenericTrees.TSVTree
#define IDH_HTML_svCollections_GenericTrees_TSVTree_AbsoluteIndex_TSVTreeNode_T_ 0x0000000D // svCollections.GenericTrees.TSVTree.AbsoluteIndex@TSVTreeNode<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree_AddChild_TSVTreeNode_T__T 0x0000000E // svCollections.GenericTrees.TSVTree.AddChild@TSVTreeNode<T>@T
#define IDH_HTML_svCollections_GenericTrees_TSVTree_BeginUpdate 0x0000000F // svCollections.GenericTrees.TSVTree.BeginUpdate
#define IDH_HTML_svCollections_GenericTrees_TSVTree_Clear  0x00000010 // svCollections.GenericTrees.TSVTree.Clear
#define IDH_HTML_svCollections_GenericTrees_TSVTree_CompactIndex 0x00000011 // svCollections.GenericTrees.TSVTree.CompactIndex
#define IDH_HTML_svCollections_GenericTrees_TSVTree_DeleteChildren_TSVTreeNode_T__Boolean 0x00000012 // svCollections.GenericTrees.TSVTree.DeleteChildren@TSVTreeNode<T>@Boolean
#define IDH_HTML_svCollections_GenericTrees_TSVTree_DeleteNode_TSVTreeNode_T__Boolean 0x00000013 // svCollections.GenericTrees.TSVTree.DeleteNode@TSVTreeNode<T>@Boolean
#define IDH_HTML_svCollections_GenericTrees_TSVTree_DoLoadUserData_TSVTreeNode_T__TStream 0x00000014 // svCollections.GenericTrees.TSVTree.DoLoadUserData@TSVTreeNode<T>@TStream
#define IDH_HTML_svCollections_GenericTrees_TSVTree_DoSaveUserData_TSVTreeNode_T__TStream 0x00000015 // svCollections.GenericTrees.TSVTree.DoSaveUserData@TSVTreeNode<T>@TStream
#define IDH_HTML_svCollections_GenericTrees_TSVTree_EndUpdate 0x00000016 // svCollections.GenericTrees.TSVTree.EndUpdate
#define IDH_HTML_svCollections_GenericTrees_TSVTree_FinishChunkHeader_TStream_Integer_Integer 0x00000017 // svCollections.GenericTrees.TSVTree.FinishChunkHeader@TStream@Integer@Integer
#define IDH_HTML_svCollections_GenericTrees_TSVTree_GenerateIndex_TSVTreeNode_T_ 0x00000018 // svCollections.GenericTrees.TSVTree.GenerateIndex@TSVTreeNode<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree_GetFirst 0x00000019 // svCollections.GenericTrees.TSVTree.GetFirst
#define IDH_HTML_svCollections_GenericTrees_TSVTree_GetFirstLevel_Integer 0x0000001A // svCollections.GenericTrees.TSVTree.GetFirstLevel@Integer
#define IDH_HTML_svCollections_GenericTrees_TSVTree_GetLast_TSVTreeNode_T_ 0x0000001B // svCollections.GenericTrees.TSVTree.GetLast@TSVTreeNode<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree_GetLastChild_TSVTreeNode_T_ 0x0000001C // svCollections.GenericTrees.TSVTree.GetLastChild@TSVTreeNode<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree_GetNext_TSVTreeNode_T_ 0x0000001D // svCollections.GenericTrees.TSVTree.GetNext@TSVTreeNode<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree_GetNextLevel_TSVTreeNode_T__Integer 0x0000001E // svCollections.GenericTrees.TSVTree.GetNextLevel@TSVTreeNode<T>@Integer
#define IDH_HTML___OVERLOADED_GetNode_svCollections_GenericTrees_TSVTree 0x0000001F // !!OVERLOADED_GetNode_svCollections.GenericTrees.TSVTree
#define IDH_HTML_svCollections_GenericTrees_TSVTree_GetNode_PVirtualNode 0x00000020 // svCollections.GenericTrees.TSVTree.GetNode@PVirtualNode
#define IDH_HTML_svCollections_GenericTrees_TSVTree_GetNode_RawByteString 0x00000021 // svCollections.GenericTrees.TSVTree.GetNode@RawByteString
#define IDH_HTML_svCollections_GenericTrees_TSVTree_GetNodeLevel_TSVTreeNode_T_ 0x00000022 // svCollections.GenericTrees.TSVTree.GetNodeLevel@TSVTreeNode<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree_GetPrevious_TSVTreeNode_T_ 0x00000023 // svCollections.GenericTrees.TSVTree.GetPrevious@TSVTreeNode<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree_GetPreviousLevel_TSVTreeNode_T__Integer 0x00000024 // svCollections.GenericTrees.TSVTree.GetPreviousLevel@TSVTreeNode<T>@Integer
#define IDH_HTML_svCollections_GenericTrees_TSVTree_HasChildren_TSVTreeNode_T_ 0x00000025 // svCollections.GenericTrees.TSVTree.HasChildren@TSVTreeNode<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree_HasParent_TSVTreeNode_T_ 0x00000026 // svCollections.GenericTrees.TSVTree.HasParent@TSVTreeNode<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree_InitNode_TSVTreeNode_T__T 0x00000027 // svCollections.GenericTrees.TSVTree.InitNode@TSVTreeNode<T>@T
#define IDH_HTML_svCollections_GenericTrees_TSVTree_InternalAddFromStream_TStream_Integer_TSVTreeNode_T_ 0x00000028 // svCollections.GenericTrees.TSVTree.InternalAddFromStream@TStream@Integer@TSVTreeNode<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree_InternalDeleteNode_TSVTreeNode_T__Boolean 0x00000029 // svCollections.GenericTrees.TSVTree.InternalDeleteNode@TSVTreeNode<T>@Boolean
#define IDH_HTML_svCollections_GenericTrees_TSVTree_IsRootNode_TSVTreeNode_T_ 0x0000002A // svCollections.GenericTrees.TSVTree.IsRootNode@TSVTreeNode<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree_IterateSubtree_TSVTreeNode_T__TIterCallback_T__Pointer 0x0000002B // svCollections.GenericTrees.TSVTree.IterateSubtree@TSVTreeNode<T>@TIterCallback<T>@Pointer
#define IDH_HTML_svCollections_GenericTrees_TSVTree_LoadFromFile_TFileName 0x0000002C // svCollections.GenericTrees.TSVTree.LoadFromFile@TFileName
#define IDH_HTML_svCollections_GenericTrees_TSVTree_LoadFromStream_TStream 0x0000002D // svCollections.GenericTrees.TSVTree.LoadFromStream@TStream
#define IDH_HTML_svCollections_GenericTrees_TSVTree_ProcessNode_TSVTreeNode_T__Boolean 0x0000002E // svCollections.GenericTrees.TSVTree.ProcessNode@TSVTreeNode<T>@Boolean
#define IDH_HTML_svCollections_GenericTrees_TSVTree_ProcessNodeAddIndex_TSVTreeNode_T_ 0x0000002F // svCollections.GenericTrees.TSVTree.ProcessNodeAddIndex@TSVTreeNode<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree_ReadChunk_TStream_Integer_TSVTreeNode_T__Integer_Integ 0x00000030 // svCollections.GenericTrees.TSVTree.ReadChunk@TStream@Integer@TSVTreeNode<T>@Integer@Integer
#define IDH_HTML_svCollections_GenericTrees_TSVTree_ReadNode_TStream_Integer_TSVTreeNode_T_ 0x00000031 // svCollections.GenericTrees.TSVTree.ReadNode@TStream@Integer@TSVTreeNode<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree_RebuildIndexes_TSVTreeNode_T_ 0x00000032 // svCollections.GenericTrees.TSVTree.RebuildIndexes@TSVTreeNode<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree_RebuildVirtualTree_PVirtualNode 0x00000033 // svCollections.GenericTrees.TSVTree.RebuildVirtualTree@PVirtualNode
#define IDH_HTML_svCollections_GenericTrees_TSVTree_SaveToFile_TFileName 0x00000034 // svCollections.GenericTrees.TSVTree.SaveToFile@TFileName
#define IDH_HTML_svCollections_GenericTrees_TSVTree_SaveToStream_TStream_TSVTreeNode_T_ 0x00000035 // svCollections.GenericTrees.TSVTree.SaveToStream@TStream@TSVTreeNode<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree_WriteChunks_TStream_TSVTreeNode_T_ 0x00000036 // svCollections.GenericTrees.TSVTree.WriteChunks@TStream@TSVTreeNode<T>
#define IDH_HTML_svCollections_GenericTrees_TSVTree_WriteNode_TStream_TSVTreeNode_T_ 0x00000037 // svCollections.GenericTrees.TSVTree.WriteNode@TStream@TSVTreeNode<T>
#define IDH_HTML___MEMBERTYPE_Properties_svCollections_GenericTrees_TSVTree 0x00000038 // !!MEMBERTYPE_Properties_svCollections.GenericTrees.TSVTree
#define IDH_HTML_svCollections_GenericTrees_TSVTree_IsEmpty 0x00000039 // svCollections.GenericTrees.TSVTree.IsEmpty
#define IDH_HTML_svCollections_GenericTrees_TSVTree_OnAfterAddChild 0x0000003A // svCollections.GenericTrees.TSVTree.OnAfterAddChild
#define IDH_HTML_svCollections_GenericTrees_TSVTree_OnFreeNode 0x0000003B // svCollections.GenericTrees.TSVTree.OnFreeNode
#define IDH_HTML_svCollections_GenericTrees_TSVTree_OnLoadNode 0x0000003C // svCollections.GenericTrees.TSVTree.OnLoadNode
#define IDH_HTML_svCollections_GenericTrees_TSVTree_OnLoadTree 0x0000003D // svCollections.GenericTrees.TSVTree.OnLoadTree
#define IDH_HTML_svCollections_GenericTrees_TSVTree_OnSaveNode 0x0000003E // svCollections.GenericTrees.TSVTree.OnSaveNode
#define IDH_HTML_svCollections_GenericTrees_TSVTree_OnSaveTree 0x0000003F // svCollections.GenericTrees.TSVTree.OnSaveTree
#define IDH_HTML_svCollections_GenericTrees_TSVTree_OwnsObjects 0x00000040 // svCollections.GenericTrees.TSVTree.OwnsObjects
#define IDH_HTML_svCollections_GenericTrees_TSVTree_RootNode 0x00000041 // svCollections.GenericTrees.TSVTree.RootNode
#define IDH_HTML_svCollections_GenericTrees_TSVTree_RootNodeCount 0x00000042 // svCollections.GenericTrees.TSVTree.RootNodeCount
#define IDH_HTML_svCollections_GenericTrees_TSVTree_TotalCount 0x00000043 // svCollections.GenericTrees.TSVTree.TotalCount
#define IDH_HTML_svCollections_GenericTrees_TSVTree_VirtualTree 0x00000044 // svCollections.GenericTrees.TSVTree.VirtualTree
#define IDH_HTML_svCollections_GenericTrees_TSVTreeNode    0x00000045 // svCollections.GenericTrees.TSVTreeNode
#define IDH_HTML___MEMBEROVERVIEW_svCollections_GenericTrees_TSVTreeNode 0x00000046 // !!MEMBEROVERVIEW_svCollections.GenericTrees.TSVTreeNode
#define IDH_HTML___MEMBERTYPE_Fields_svCollections_GenericTrees_TSVTreeNode 0x00000047 // !!MEMBERTYPE_Fields_svCollections.GenericTrees.TSVTreeNode
#define IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FChildCount 0x00000048 // svCollections.GenericTrees.TSVTreeNode.FChildCount
#define IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FFirstChild 0x00000049 // svCollections.GenericTrees.TSVTreeNode.FFirstChild
#define IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FLastChild 0x0000004A // svCollections.GenericTrees.TSVTreeNode.FLastChild
#define IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FNextSibling 0x0000004B // svCollections.GenericTrees.TSVTreeNode.FNextSibling
#define IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FNodeIndex 0x0000004C // svCollections.GenericTrees.TSVTreeNode.FNodeIndex
#define IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FParent 0x0000004D // svCollections.GenericTrees.TSVTreeNode.FParent
#define IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FPrevSibling 0x0000004E // svCollections.GenericTrees.TSVTreeNode.FPrevSibling
#define IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FTotalCount 0x0000004F // svCollections.GenericTrees.TSVTreeNode.FTotalCount
#define IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FValue 0x00000050 // svCollections.GenericTrees.TSVTreeNode.FValue
#define IDH_HTML_svCollections_GenericTrees_TSVTreeNode_FVirtualNode 0x00000051 // svCollections.GenericTrees.TSVTreeNode.FVirtualNode
#define IDH_HTML___MEMBERTYPE_Methods_svCollections_GenericTrees_TSVTreeNode 0x00000052 // !!MEMBERTYPE_Methods_svCollections.GenericTrees.TSVTreeNode
#define IDH_HTML_svCollections_GenericTrees_TSVTreeNode_GetOwner 0x00000053 // svCollections.GenericTrees.TSVTreeNode.GetOwner
#define IDH_HTML_svCollections_GenericTrees_TSVTreeNode_HasChildren 0x00000054 // svCollections.GenericTrees.TSVTreeNode.HasChildren
#define IDH_HTML_svCollections_GenericTrees_TSVTreeNode_HasParent 0x00000055 // svCollections.GenericTrees.TSVTreeNode.HasParent
#define IDH_HTML_svCollections_GenericTrees_TSVTreeNode_SVTreeFromNode_TSVTreeNode_T_ 0x00000056 // svCollections.GenericTrees.TSVTreeNode.SVTreeFromNode@TSVTreeNode<T>
#define IDH_HTML___RECORDS_svCollections_GenericTrees      0x00000057 // !!RECORDS_svCollections.GenericTrees
#define IDH_HTML_svCollections_GenericTrees_TSVBaseChunk   0x00000058 // svCollections.GenericTrees.TSVBaseChunk
#define IDH_HTML_svCollections_GenericTrees_TSVBaseChunkBody 0x00000059 // svCollections.GenericTrees.TSVBaseChunkBody
#define IDH_HTML_svCollections_GenericTrees_TSVChunkHeader 0x0000005A // svCollections.GenericTrees.TSVChunkHeader
#define IDH_HTML___TYPES_svCollections_GenericTrees        0x0000005B // !!TYPES_svCollections.GenericTrees
#define IDH_HTML_svCollections_GenericTrees_ProcAfterAddNode 0x0000005C // svCollections.GenericTrees.ProcAfterAddNode
#define IDH_HTML_svCollections_GenericTrees_ProcOnFreeNode 0x0000005D // svCollections.GenericTrees.ProcOnFreeNode
#define IDH_HTML_svCollections_GenericTrees_ProcOnSaveNode 0x0000005E // svCollections.GenericTrees.ProcOnSaveNode
#define IDH_HTML_svCollections_GenericTrees_ProcSaveTree   0x0000005F // svCollections.GenericTrees.ProcSaveTree
#define IDH_HTML_svCollections_GenericTrees_TIterCallBack  0x00000060 // svCollections.GenericTrees.TIterCallBack
#define IDH_HTML_svCollections_GenericTrees_TSVMagicID     0x00000061 // svCollections.GenericTrees.TSVMagicID
#define IDH_HTML___CONSTANTS_svCollections_GenericTrees    0x00000062 // !!CONSTANTS_svCollections.GenericTrees
#define IDH_HTML_svCollections_GenericTrees_BaseChunk      0x00000063 // svCollections.GenericTrees.BaseChunk
#define IDH_HTML_svCollections_GenericTrees_CaptionChunk   0x00000064 // svCollections.GenericTrees.CaptionChunk
#define IDH_HTML_svCollections_GenericTrees_NodeChunk      0x00000065 // svCollections.GenericTrees.NodeChunk
#define IDH_HTML_svCollections_GenericTrees_SVMagicID      0x00000066 // svCollections.GenericTrees.SVMagicID
#define IDH_HTML_svCollections_GenericTrees_SVTreeStreamVersion 0x00000067 // svCollections.GenericTrees.SVTreeStreamVersion
#define IDH_HTML_svCollections_GenericTrees_UserChunk      0x00000068 // svCollections.GenericTrees.UserChunk
#define IDH_HTML_svCollections_Trees                       0x00000069 // svCollections.Trees
#define IDH_HTML___CLASSES_svCollections_Trees             0x0000006A // !!CLASSES_svCollections.Trees
#define IDH_HTML_svCollections_Trees_TSVBaseVirtualTreeHelper 0x0000006B // svCollections.Trees.TSVBaseVirtualTreeHelper
#define IDH_HTML___MEMBEROVERVIEW_svCollections_Trees_TSVBaseVirtualTreeHelper 0x0000006C // !!MEMBEROVERVIEW_svCollections.Trees.TSVBaseVirtualTreeHelper
#define IDH_HTML___MEMBERTYPE_Methods_svCollections_Trees_TSVBaseVirtualTreeHelper 0x0000006D // !!MEMBERTYPE_Methods_svCollections.Trees.TSVBaseVirtualTreeHelper
#define IDH_HTML_svCollections_Trees_TSVBaseVirtualTreeHelper_GenerateIndex_PVirtualNode 0x0000006E // svCollections.Trees.TSVBaseVirtualTreeHelper.GenerateIndex@PVirtualNode
#define IDH_HTML_svCollections_Trees_TSVBaseVirtualTreeHelper_GetSVNode_PVirtualNode_TSVTree 0x0000006F // svCollections.Trees.TSVBaseVirtualTreeHelper.GetSVNode@PVirtualNode@TSVTree
#define IDH_HTML_svCollections_Trees_TSVTree               0x00000070 // svCollections.Trees.TSVTree
#define IDH_HTML___MEMBEROVERVIEW_svCollections_Trees_TSVTree 0x00000071 // !!MEMBEROVERVIEW_svCollections.Trees.TSVTree
#define IDH_HTML_svCollections_Trees_TSVTree_Create_Boolean_Integer 0x00000072 // svCollections.Trees.TSVTree.Create@Boolean@Integer
#define IDH_HTML_svCollections_Trees_TSVTree_Destroy       0x00000073 // svCollections.Trees.TSVTree.Destroy
#define IDH_HTML___MEMBERTYPE_Methods_svCollections_Trees_TSVTree 0x00000074 // !!MEMBERTYPE_Methods_svCollections.Trees.TSVTree
#define IDH_HTML_svCollections_Trees_TSVTree_AbsoluteIndex_PSVTreeNode 0x00000075 // svCollections.Trees.TSVTree.AbsoluteIndex@PSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTree_AddChild_PSVTreeNode_Pointer 0x00000076 // svCollections.Trees.TSVTree.AddChild@PSVTreeNode@Pointer
#define IDH_HTML_svCollections_Trees_TSVTree_BeginUpdate   0x00000077 // svCollections.Trees.TSVTree.BeginUpdate
#define IDH_HTML_svCollections_Trees_TSVTree_Clear         0x00000078 // svCollections.Trees.TSVTree.Clear
#define IDH_HTML_svCollections_Trees_TSVTree_CompactIndex  0x00000079 // svCollections.Trees.TSVTree.CompactIndex
#define IDH_HTML_svCollections_Trees_TSVTree_DeleteChildren_PSVTreeNode_Boolean 0x0000007A // svCollections.Trees.TSVTree.DeleteChildren@PSVTreeNode@Boolean
#define IDH_HTML_svCollections_Trees_TSVTree_DeleteNode_PSVTreeNode_Boolean 0x0000007B // svCollections.Trees.TSVTree.DeleteNode@PSVTreeNode@Boolean
#define IDH_HTML_svCollections_Trees_TSVTree_DoLoadUserData_PSVTreeNode_TStream 0x0000007C // svCollections.Trees.TSVTree.DoLoadUserData@PSVTreeNode@TStream
#define IDH_HTML_svCollections_Trees_TSVTree_DoSaveUserData_PSVTreeNode_TStream 0x0000007D // svCollections.Trees.TSVTree.DoSaveUserData@PSVTreeNode@TStream
#define IDH_HTML_svCollections_Trees_TSVTree_EndUpdate     0x0000007E // svCollections.Trees.TSVTree.EndUpdate
#define IDH_HTML_svCollections_Trees_TSVTree_FindNode_string 0x0000007F // svCollections.Trees.TSVTree.FindNode@string
#define IDH_HTML_svCollections_Trees_TSVTree_FinishChunkHeader_TStream_Integer_Integer 0x00000080 // svCollections.Trees.TSVTree.FinishChunkHeader@TStream@Integer@Integer
#define IDH_HTML_svCollections_Trees_TSVTree_GenerateIndex_PSVTreeNode 0x00000081 // svCollections.Trees.TSVTree.GenerateIndex@PSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTree_GetFirst      0x00000082 // svCollections.Trees.TSVTree.GetFirst
#define IDH_HTML_svCollections_Trees_TSVTree_GetFirstLevel_Integer 0x00000083 // svCollections.Trees.TSVTree.GetFirstLevel@Integer
#define IDH_HTML_svCollections_Trees_TSVTree_GetLast_PSVTreeNode 0x00000084 // svCollections.Trees.TSVTree.GetLast@PSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTree_GetLastChild_PSVTreeNode 0x00000085 // svCollections.Trees.TSVTree.GetLastChild@PSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTree_GetNext_PSVTreeNode 0x00000086 // svCollections.Trees.TSVTree.GetNext@PSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTree_GetNextLevel_PSVTreeNode_Integer 0x00000087 // svCollections.Trees.TSVTree.GetNextLevel@PSVTreeNode@Integer
#define IDH_HTML___OVERLOADED_GetNode_svCollections_Trees_TSVTree 0x00000088 // !!OVERLOADED_GetNode_svCollections.Trees.TSVTree
#define IDH_HTML_svCollections_Trees_TSVTree_GetNode_PVirtualNode 0x00000089 // svCollections.Trees.TSVTree.GetNode@PVirtualNode
#define IDH_HTML_svCollections_Trees_TSVTree_GetNode_RawByteString 0x0000008A // svCollections.Trees.TSVTree.GetNode@RawByteString
#define IDH_HTML_svCollections_Trees_TSVTree_GetNodeLevel_PSVTreeNode 0x0000008B // svCollections.Trees.TSVTree.GetNodeLevel@PSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTree_GetPrevious_PSVTreeNode 0x0000008C // svCollections.Trees.TSVTree.GetPrevious@PSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTree_GetPreviousLevel_PSVTreeNode_Integer 0x0000008D // svCollections.Trees.TSVTree.GetPreviousLevel@PSVTreeNode@Integer
#define IDH_HTML_svCollections_Trees_TSVTree_HasChildren_PSVTreeNode 0x0000008E // svCollections.Trees.TSVTree.HasChildren@PSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTree_HasParent_PSVTreeNode 0x0000008F // svCollections.Trees.TSVTree.HasParent@PSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTree_InitNode_PSVTreeNode_Pointer 0x00000090 // svCollections.Trees.TSVTree.InitNode@PSVTreeNode@Pointer
#define IDH_HTML_svCollections_Trees_TSVTree_InternalAddFromStream_TStream_Integer_PSVTreeNode 0x00000091 // svCollections.Trees.TSVTree.InternalAddFromStream@TStream@Integer@PSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTree_InternalDeleteNode_PSVTreeNode_Boolean 0x00000092 // svCollections.Trees.TSVTree.InternalDeleteNode@PSVTreeNode@Boolean
#define IDH_HTML_svCollections_Trees_TSVTree_IsRootNode_PSVTreeNode 0x00000093 // svCollections.Trees.TSVTree.IsRootNode@PSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTree_IterateSubtree_PSVTreeNode_TIterCallback_Pointer 0x00000094 // svCollections.Trees.TSVTree.IterateSubtree@PSVTreeNode@TIterCallback@Pointer
#define IDH_HTML_svCollections_Trees_TSVTree_LoadFromFile_TFileName 0x00000095 // svCollections.Trees.TSVTree.LoadFromFile@TFileName
#define IDH_HTML_svCollections_Trees_TSVTree_LoadFromStream_TStream 0x00000096 // svCollections.Trees.TSVTree.LoadFromStream@TStream
#define IDH_HTML_svCollections_Trees_TSVTree_ReadChunk_TStream_Integer_PSVTreeNode_Integer_Integer 0x00000097 // svCollections.Trees.TSVTree.ReadChunk@TStream@Integer@PSVTreeNode@Integer@Integer
#define IDH_HTML_svCollections_Trees_TSVTree_ReadNode_TStream_Integer_PSVTreeNode 0x00000098 // svCollections.Trees.TSVTree.ReadNode@TStream@Integer@PSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTree_RebuildIndexes_PSVTreeNode 0x00000099 // svCollections.Trees.TSVTree.RebuildIndexes@PSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTree_RebuildVirtualTree_PVirtualNode 0x0000009A // svCollections.Trees.TSVTree.RebuildVirtualTree@PVirtualNode
#define IDH_HTML_svCollections_Trees_TSVTree_SaveToFile_TFileName 0x0000009B // svCollections.Trees.TSVTree.SaveToFile@TFileName
#define IDH_HTML_svCollections_Trees_TSVTree_SaveToStream_TStream_PSVTreeNode 0x0000009C // svCollections.Trees.TSVTree.SaveToStream@TStream@PSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTree_WriteChunks_TStream_PSVTreeNode 0x0000009D // svCollections.Trees.TSVTree.WriteChunks@TStream@PSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTree_WriteNode_TStream_PSVTreeNode 0x0000009E // svCollections.Trees.TSVTree.WriteNode@TStream@PSVTreeNode
#define IDH_HTML___MEMBERTYPE_Properties_svCollections_Trees_TSVTree 0x0000009F // !!MEMBERTYPE_Properties_svCollections.Trees.TSVTree
#define IDH_HTML_svCollections_Trees_TSVTree_IsEmpty       0x000000A0 // svCollections.Trees.TSVTree.IsEmpty
#define IDH_HTML_svCollections_Trees_TSVTree_OwnsObjects   0x000000A1 // svCollections.Trees.TSVTree.OwnsObjects
#define IDH_HTML_svCollections_Trees_TSVTree_RootNode      0x000000A2 // svCollections.Trees.TSVTree.RootNode
#define IDH_HTML_svCollections_Trees_TSVTree_RootNodeCount 0x000000A3 // svCollections.Trees.TSVTree.RootNodeCount
#define IDH_HTML_svCollections_Trees_TSVTree_TotalCount    0x000000A4 // svCollections.Trees.TSVTree.TotalCount
#define IDH_HTML_svCollections_Trees_TSVTree_UseCustomIndex 0x000000A5 // svCollections.Trees.TSVTree.UseCustomIndex
#define IDH_HTML_svCollections_Trees_TSVTree_VirtualTree   0x000000A6 // svCollections.Trees.TSVTree.VirtualTree
#define IDH_HTML___MEMBERTYPE_Events_svCollections_Trees_TSVTree 0x000000A7 // !!MEMBERTYPE_Events_svCollections.Trees.TSVTree
#define IDH_HTML_svCollections_Trees_TSVTree_OnAfterAddChild 0x000000A8 // svCollections.Trees.TSVTree.OnAfterAddChild
#define IDH_HTML_svCollections_Trees_TSVTree_OnFreeNode    0x000000A9 // svCollections.Trees.TSVTree.OnFreeNode
#define IDH_HTML_svCollections_Trees_TSVTree_OnLoadNode    0x000000AA // svCollections.Trees.TSVTree.OnLoadNode
#define IDH_HTML_svCollections_Trees_TSVTree_OnLoadTree    0x000000AB // svCollections.Trees.TSVTree.OnLoadTree
#define IDH_HTML_svCollections_Trees_TSVTree_OnSaveNode    0x000000AC // svCollections.Trees.TSVTree.OnSaveNode
#define IDH_HTML_svCollections_Trees_TSVTree_OnSaveTree    0x000000AD // svCollections.Trees.TSVTree.OnSaveTree
#define IDH_HTML_svCollections_Trees_TSVTreeNode           0x000000AE // svCollections.Trees.TSVTreeNode
#define IDH_HTML___MEMBEROVERVIEW_svCollections_Trees_TSVTreeNode 0x000000AF // !!MEMBEROVERVIEW_svCollections.Trees.TSVTreeNode
#define IDH_HTML___MEMBERTYPE_Fields_svCollections_Trees_TSVTreeNode 0x000000B0 // !!MEMBERTYPE_Fields_svCollections.Trees.TSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTreeNode_FChildCount 0x000000B1 // svCollections.Trees.TSVTreeNode.FChildCount
#define IDH_HTML_svCollections_Trees_TSVTreeNode_FFirstChild 0x000000B2 // svCollections.Trees.TSVTreeNode.FFirstChild
#define IDH_HTML_svCollections_Trees_TSVTreeNode_FLastChild 0x000000B3 // svCollections.Trees.TSVTreeNode.FLastChild
#define IDH_HTML_svCollections_Trees_TSVTreeNode_FNextSibling 0x000000B4 // svCollections.Trees.TSVTreeNode.FNextSibling
#define IDH_HTML_svCollections_Trees_TSVTreeNode_FNodeIndex 0x000000B5 // svCollections.Trees.TSVTreeNode.FNodeIndex
#define IDH_HTML_svCollections_Trees_TSVTreeNode_FParent   0x000000B6 // svCollections.Trees.TSVTreeNode.FParent
#define IDH_HTML_svCollections_Trees_TSVTreeNode_FPrevSibling 0x000000B7 // svCollections.Trees.TSVTreeNode.FPrevSibling
#define IDH_HTML_svCollections_Trees_TSVTreeNode_FTotalCount 0x000000B8 // svCollections.Trees.TSVTreeNode.FTotalCount
#define IDH_HTML_svCollections_Trees_TSVTreeNode_FValue    0x000000B9 // svCollections.Trees.TSVTreeNode.FValue
#define IDH_HTML_svCollections_Trees_TSVTreeNode_FVirtualNode 0x000000BA // svCollections.Trees.TSVTreeNode.FVirtualNode
#define IDH_HTML___MEMBERTYPE_Methods_svCollections_Trees_TSVTreeNode 0x000000BB // !!MEMBERTYPE_Methods_svCollections.Trees.TSVTreeNode
#define IDH_HTML_svCollections_Trees_TSVTreeNode_GetOwner  0x000000BC // svCollections.Trees.TSVTreeNode.GetOwner
#define IDH_HTML_svCollections_Trees_TSVTreeNode_HasChildren 0x000000BD // svCollections.Trees.TSVTreeNode.HasChildren
#define IDH_HTML_svCollections_Trees_TSVTreeNode_HasParent 0x000000BE // svCollections.Trees.TSVTreeNode.HasParent
#define IDH_HTML___FUNCTIONS_svCollections_Trees           0x000000BF // !!FUNCTIONS_svCollections.Trees
#define IDH_HTML_svCollections_Trees_SVTreeFromNode_PSVTreeNode 0x000000C0 // svCollections.Trees.SVTreeFromNode@PSVTreeNode
#define IDH_HTML___RECORDS_svCollections_Trees             0x000000C1 // !!RECORDS_svCollections.Trees
#define IDH_HTML_svCollections_Trees_TSVBaseChunk          0x000000C2 // svCollections.Trees.TSVBaseChunk
#define IDH_HTML_svCollections_Trees_TSVBaseChunkBody      0x000000C3 // svCollections.Trees.TSVBaseChunkBody
#define IDH_HTML_svCollections_Trees_TSVChunkHeader        0x000000C4 // svCollections.Trees.TSVChunkHeader
#define IDH_HTML___TYPES_svCollections_Trees               0x000000C5 // !!TYPES_svCollections.Trees
#define IDH_HTML_svCollections_Trees_ProcAfterAddNode      0x000000C6 // svCollections.Trees.ProcAfterAddNode
#define IDH_HTML_svCollections_Trees_ProcOnFreeNode        0x000000C7 // svCollections.Trees.ProcOnFreeNode
#define IDH_HTML_svCollections_Trees_ProcOnSaveNode        0x000000C8 // svCollections.Trees.ProcOnSaveNode
#define IDH_HTML_svCollections_Trees_ProcSaveTree          0x000000C9 // svCollections.Trees.ProcSaveTree
#define IDH_HTML_svCollections_Trees_PSVTreeNode           0x000000CA // svCollections.Trees.PSVTreeNode
#define IDH_HTML_svCollections_Trees_TIterCallBack         0x000000CB // svCollections.Trees.TIterCallBack
#define IDH_HTML_svCollections_Trees_TSVMagicID            0x000000CC // svCollections.Trees.TSVMagicID
#define IDH_HTML___CONSTANTS_svCollections_Trees           0x000000CD // !!CONSTANTS_svCollections.Trees
#define IDH_HTML_svCollections_Trees_BaseChunk             0x000000CE // svCollections.Trees.BaseChunk
#define IDH_HTML_svCollections_Trees_CaptionChunk          0x000000CF // svCollections.Trees.CaptionChunk
#define IDH_HTML_svCollections_Trees_NodeChunk             0x000000D0 // svCollections.Trees.NodeChunk
#define IDH_HTML_svCollections_Trees_SVMagicID             0x000000D1 // svCollections.Trees.SVMagicID
#define IDH_HTML_svCollections_Trees_SVTreeStreamVersion   0x000000D2 // svCollections.Trees.SVTreeStreamVersion
#define IDH_HTML_svCollections_Trees_UserChunk             0x000000D3 // svCollections.Trees.UserChunk
#define IDH_HTML___FILES                                   0x000000D4 // !!FILES
#define IDH_HTML_svCollections_GenericTrees_pas            0x000000D5 // svCollections.GenericTrees.pas
#define IDH_HTML_svCollections_Trees_pas                   0x000000D6 // svCollections.Trees.pas
